
modLoader="javafml"
loaderVersion="[41,)"
#issueTrackerURL="https://github.com/vectorwing/FarmersDelight/issues"
license="MIT License"

[[mods]]
modId="nethersdelight"
version="1.19-3.0"
displayName="Nether's Delight"
# updateJSONURL=""
#displayURL="https://github.com/vectorwing/FarmersDelight"
logoFile="logo.png"
logoBlur=false
credits="Umpaz, SoyTutta, and Sammy;"
authors="umpaz"
description="A nether expansion for the Farmer's Delight mod!"
itemIcon="nethersdelight:blackstone_stove"
configBackground="minecraft:textures/block/netherrack.png"

[[dependencies.nethersdelight]]
    modId="forge"
    mandatory=true
    versionRange="[41.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nethersdelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nethersdelight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.1.2,)"
    ordering="NONE"
    side="BOTH"
